project_name: rdapp

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd
    binary: rdapp
    ldflags:
      - -X main.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

brews:
  - tap:
      owner: kishaningithub
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kishaningithub/rdapp
    description: rdapp - redshift data api postgres proxy
    license: MIT

nfpms:
  - id: rdapp
    package_name: rdapp
    homepage: https://github.com/kishaningithub/rdapp
    description: rdapp - redshift data api postgres proxy
    maintainer: Kishan B <kishancs46@gmail.com>
    license: MIT
    formats:
      - apk
      - deb
      - rpm

kos:
  - main: ./cmd/
    base_image: alpine
    repository: ghcr.io/kishaningithub/rdapp
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
