name: Commentor

on:
  issue_comment:
    types: [created]
  push: 

jobs:
  terraform_plan:
    name: terraform_plan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Invoke Terraform
        run: |
          echo "Comment Body: ${{github.event.comment.body}}"
