name: Commentor

on:
  issue_comment:
    types: [created]

jobs:
  terraform_plan:
    if: github.event_name == 'push'
    name: terraform_plan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Invoke Terraform
        run: |
          cho "Comment Body: ${{github.event.comment.body}}"
